### ISSUE TITLE
What about an manual?

### ISSUE THREAD

**Issue by nunotexbsd** [Code-Hex/Neo-cowsay#15]
Hello,

I've ported neo-cowsay to FreeBSD and I'm waiting it gets imported to ports: [PR250771](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250771)

What about an manual?

Original project [manual](https://github.com/schacon/cowsay/blob/master/cowsay.1) is written in man legacy formatting language but I can write it from scratch in [mdoc](https://mandoc.bsd.lv/).

What do you think?

BTW --super option is awesome!

Thanks,

Nuno Teixeira

**Comment by Code-Hex** [comment]
Hi @nunotexbsd, Thanks for creating this issue.

I agree to add the manual. I will try to write the manual but I need to take a little more time 🙏

**Comment by nunotexbsd** [comment]
Well I had time to write it if you want and you can change manual content later because its your project :)

Thanks

**Comment by Code-Hex** [comment]
@nunotexbsd I'm sorry too late for supporting.
It will be included in the next release.

Thank you so much.
