### ISSUE TITLE
Cannot install via `go install` since v2.0.2

### ISSUE THREAD

**Issue by civita** [Code-Hex/Neo-cowsay#49]
I use `go install github.com/Code-Hex/Neo-cowsay/v2/cmd/cowsay@latest` to install the latest version, but it shows the following error:

```shell
go install: github.com/Code-Hex/Neo-cowsay/v2/cmd/cowsay@latest: module github.com/Code-Hex/Neo-cowsay/v2@latest found (v2.0.3), but does not contain package github.com/Code-Hex/Neo-cowsay/v2/cmd/cowsay
```

I think it is somehow related to subdirectory versioning.

**go version** `go1.17.4 linux/amd64`

**Comment by Code-Hex** [comment]
@civita Thanks for creating the issue and submitting your PR.
I have described why I separate modules here.
https://github.com/Code-Hex/Neo-cowsay/issues/48#issuecomment-981513462

I think your PR cannot resolve contains my concerns.

So I will investigate this problem. Please just a moment :bow:

**Comment by civita** [comment]
Hi @Code-Hex,

Just viewed and got your concerns in #48 for separating modules! For `cmd`, I think it is possible for just use `github.com/Code-Hex/Neo-cowsay/cmd` or `github.com/Code-Hex/Neo-cowsay/cmd/v2`. The second one is followed by naming convention specified [here](https://github.com/golang/go/wiki/Modules#publishing-a-release). What do you think about it? Thank you.

**Comment by Code-Hex** [comment]
@civita Thanks to help me!
You may install via `go install github.com/Code-Hex/Neo-cowsay/cmd/v2/cowsay@latest` now.

Could you close this issue if you could install?

**Comment by civita** [comment]
Thanks. It works as expected now!
