### ISSUE TITLE
Does not have ansi escape sequence color support

### ISSUE THREAD

**Issue by zloyle** [Code-Hex/Neo-cowsay#51]
Trying to load a cow that works with og perl cowsay that has an image converted to ansi escape sequences does nothing but print the raw text.

Is this the expected behavior or is color support not included yet at this point?

https://raw.githubusercontent.com/charc0al/cowsay-files/master/cows/butcher.cow

 cowsay -f butcher Testing
 _________
< Testing >
 ---------
# Billy Butcher (The Boys)
# by @roblevypixels
# Generated with Charc0al's cowsay file converter http://charc0al.github.io/cowsay-files/converter

$x = "\e[49m  ";          #reset color
$t = "\ ";
$a = "\e[48;5;235m  ";
$b = "\e[48;5;234m  ";
$c = "\e[48;5;233m  ";
$d = "\e[48;5;236m  ";
$e = "\e[48;5;237m  ";
$f = "\e[48;5;223m  ";
$g = "\e[48;5;238m  ";
$h = "\e[48;5;231m  ";
$i = "\e[48;5;94m  ";
$j = "\e[48;5;180m  ";
$k = "\e[48;5;137m  ";
$l = "\e[48;5;138m  ";
$m = "\e[48;5;239m  ";
$n = "\e[48;5;181m  ";
$o = "\e[48;5;244m  ";
$p = "\e[48;5;66m  ";
$q = "\e[48;5;23m  ";
$r = "\e[48;5;250m  ";
$s = "\e[48;5;109m  ";
$u = "\e[48;5;251m  ";
$v = "\e[48;5;248m  ";
$w = "\e[48;5;246m  ";

<SNIP>

**Comment by Code-Hex** [comment]
Thanks for reporting!
this is not easy problem. I have to implement a small perl vm because the original cowsay is relied on the perl syntax.
I can handle with up priority if you sponsored me. thanks

**Comment by zloyle** [comment]
Understood. thank you.

**Comment by itsmeboy0** [comment]
@zloyle Do not close this as this has not been resolved yet.
