### ISSUE TITLE
How to use external cowfiles?

### ISSUE THREAD

**Issue by i0ntempest** [Code-Hex/Neo-cowsay#56]
I have written my own cowfile which works fine with the old cowsay if I specify the path to it. However neo cowsay compiles cowfiles into the binary, and if I try to reference the external one I get:
```
$ cowsay -f Documents/Scripts/fujao.cow aaa
cowsay: could not find Documents/Scripts/fujao.cow cowfile
```
How do I get around this?

**Comment by Code-Hex** [comment]
@i0ntempest Hello!
You can specify the path to `COWPATH` (see: https://github.com/Code-Hex/Neo-cowsay/pull/33#issue-1046979554) like below then you can specify the cow file

```sh
$ COWPATH="Documents/Scripts" cowsay -f fujao aaa
```
